version: "3.8"
volumes:
  etc_wireguard:

services:
  wg-easy:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this points to your Dockerfile
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=144.126.138.131
      - PASSWORD=admin123
      # Other environment variables can be uncommented and used as required
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "5000:51821/tcp"  # Make sure this is the correct port configuration for your service
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
